trigger:
  branches:
    include: 
    - main
variables:
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'sachithra-docker-hub'
  imageRepository: 'sachithram/dotnet-mvc-demo'
  containerRegistry: 'docker.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
stages:
# Build Stage
- stage: BuildImage
  jobs:
  - job: Build
    pool: myUbuntuAgent

    steps:
    # Build container image
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'build'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest

    # Push container image
    - task: Docker@2
      displayName: 'Push Docker image'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'push'
        tags: |
          $(tag)
          latest

